---
- hosts: all
  remote_user: edison
  tasks:
  - name: copy new spm-file app
    copy: src=lib/spm-file dest=/bin/ mode=0755
    become: yes

  - name: copy new pmc-file app
    copy: src=lib/pmc-file dest=/bin/ mode=0755
    become: yes

  - name: copy new wams-config app
    copy: src=lib/wams-config dest=/bin/ mode=0755
    become: yes

  - name: copy new videk app with updated software version
    copy: src=lib/videk dest=/bin/ mode=0755
    become: yes

  - name: copy new spm-file systemd service
    copy: src=systemd/spm-file.service dest=/lib/systemd/system/
    become: yes

  - name: copy new pmc-file systemd service
    copy: src=systemd/pmc-file.service dest=/lib/systemd/system/
    become: yes

  - name: copy new wams-config systemd service
    copy: src=systemd/wams-config.service dest=/lib/systemd/system/
    become: yes

  - name: systemctl daemon reload
    shell: systemctl daemon-reload
    become: yes

  - name: stop securededison-configure service
    shell: systemctl stop securededison-configure.service
    become: yes

  - name: disable securededison-configure service
    shell: systemctl disable securededison-configure.service
    become: yes

  - name: stop securededison service
    shell: systemctl stop securededison.service
    become: yes

  - name: disable securededison service
    shell: systemctl disable securededison.service
    become: yes

  - name: stop spm-file service
    shell: systemctl stop spm-file.service
    become: yes

  - name: stop pmc-file service
    shell: systemctl stop pmc-file.service
    become: yes

  - name: disable spm-file service
    shell: systemctl disable spm-file.service
    become: yes

  - name: disable pmc-file service
    shell: systemctl disable pmc-file.service
    become: yes

  - name: stop videk service
    shell: systemctl stop videk.service
    become: yes

  - name: enable wams-config service
    shell: systemctl enable wams-config.service
    become: yes

  - name: start wams-config service
    shell: systemctl start wams-config.service
    become: yes
