---
- hosts: all
  remote_user: edison
  tasks:
  - name: extract dependencies
    unarchive: src=dependencies.tar.gz dest=/var/lib
    become: yes

  - name: install dependencies
    shell: dpkg -i /var/lib/dependencies/*.deb
    become: yes

  - name: remove dependencies
    file: path=/var/lib/dependencies state=absent
    become: yes

  - name: extract securededison
    unarchive: src=securededison.tar.gz dest=/var/lib
    become: yes
