---
- hosts: all
  remote_user: edison
  tasks:
  - name: remove .ansible directory from home
    file: path=/home/edison/.ansible state=absent

  - name: extract dependencies
    unarchive: src=dependencies.tar.gz dest=/var/lib
    become: yes

  - name: install dependencies
    shell: dpkg -i /var/lib/dependencies/*.deb
    become: yes

  - name: remove dependencies
    file: path=/var/lib/dependencies state=absent
    become: yes

  - name: extract securededison
    unarchive: src=securededison.tar.gz dest=/var/lib
    become: yes

  - name: copy new sunseed parser
    copy: src=lib/sunseed-parser.js dest=/usr/lib/nodejs/
    become: yes

  - name: copy new videk app with updated software version
    copy: src=lib/videk dest=/bin/ mode=0755
    become: yes

  - name: copy new wams-config app
    copy: src=lib/wams-config dest=/bin/ mode=0755
    become: yes

  - name: copy securededison-configure systemd service
    copy: src=systemd/securededison-configure.service dest=/lib/systemd/system/
    become: yes

  - name: copy new spm-file systemd service
    copy: src=systemd/spm-file.service dest=/lib/systemd/system/
    become: yes

  - name: copy new pmc-file systemd service
    copy: src=systemd/pmc-file.service dest=/lib/systemd/system/
    become: yes

  - name: systemctl daemon reload
    shell: systemctl daemon-reload
    become: yes

  - name: stop videk service
    shell: systemctl stop videk.service
    become: yes

  - name: stop spm service
    shell: systemctl stop spm.service
    become: yes

  - name: enable wams-config service
    shell: systemctl enable wams-config.service
    become: yes

  - name: start wams-config service
    shell: systemctl start wams-config.service
    become: yes

  - name: enable securededison-configure systemd service
    shell: systemctl enable securededison-configure.service
    become: yes

  - name: start securededison-configure systemd service
    shell: systemctl start securededison-configure.service
    become: yes
