#!/usr/bin/env bash

/bin/stty -F /dev/ttyMFD1 115200 cs8 parodd -cstopb

spm=false
pmc=false

while read line; do
	if [[ "$line" == *"SPM"* ]]; then
		echo "$line"
		spm=true
		echo "Configured SPM service."
		break
	elif [[ "$line" == *"PMC"* ]]; then
		echo "$line"
		pmc=true
		echo "Configured PMC service."
		break
	fi
done < /dev/ttyMFD1

autoconf=/var/lib/securededison/config/autoconf.json

if $spm; then
	sed -i -e 's/WAMS_global_measurements/spm/g' "$autoconf"
	/bin/systemctl enable spm-file.service
	/bin/systemctl start spm-file.service &
	echo "Started SPM service."
elif $pmc; then
	sed -i -e 's/WAMS_global_measurements/pmc/g' "$autoconf"
	/var/lib/securededison/config/autoconf.json
	/bin/systemctl enable pmc-file.service
	/bin/systemctl start pmc-file.service &
	echo "Started PMC service."
fi
